import type { Metadata } from "next";
import localFont from "next/font/local";

import "./globals.css";
import Appbar from "@/components/Appbar";
const graphik = localFont({
  src: "../public/fonts/Graphik Family/Graphik-Regular-Trial.otf",
  weight: "400",
  style: "normal",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${graphik.className} `}>
        {<Appbar />}
        {children}
      </body>
    </html>
  );
}
